/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/banner.vue')['default']
    BigData: typeof import('./src/components/bigData.vue')['default']
    ButtonAddReport: typeof import('./src/components/e-Service/object/buttonAddReport.vue')['default']
    ButtonDataSourceListTable: typeof import('./src/components/e-Service/object/buttonDataSourceListTable.vue')['default']
    ChangeLang: typeof import('./src/components/changeLang.vue')['default']
    EService: typeof import('./src/components/e-Service/eService.vue')['default']
    Footer: typeof import('./src/components/base/footer.vue')['default']
    Iot: typeof import('./src/components/iot.vue')['default']
    Navbar: typeof import('./src/components/base/navbar.vue')['default']
    ReportProduct: typeof import('./src/components/e-Service/reportProduct.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceCard: typeof import('./src/components/e-Service/serviceCard.vue')['default']
    SuggestProduct: typeof import('./src/components/e-Service/suggestProduct.vue')['default']
    TagReportType: typeof import('./src/components/e-Service/object/tagReportType.vue')['default']
  }
}
